/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massmanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author tuhin
 */
public class MainWin extends javax.swing.JFrame {
        public String autoOpen="no";
    /**
     * Creates new form MainWin
     */
    public MainWin() {
        initComponents();
        setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/heavy.png")));
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addborder = new javax.swing.JButton();
        editborder = new javax.swing.JButton();
        borderinfo = new javax.swing.JButton();
        removeborder = new javax.swing.JButton();
        balance = new javax.swing.JButton();
        mill = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        addbazar = new javax.swing.JButton();
        editbazar = new javax.swing.JButton();
        bazardate = new javax.swing.JButton();
        bazarlist = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        develop = new javax.swing.JLabel();
        aboutme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Mass Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        addborder.setBackground(new java.awt.Color(0, 124, 220));
        addborder.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        addborder.setForeground(new java.awt.Color(255, 255, 255));
        addborder.setText("Add Border");
        addborder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addborder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addborderActionPerformed(evt);
            }
        });

        editborder.setBackground(new java.awt.Color(0, 124, 220));
        editborder.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        editborder.setForeground(new java.awt.Color(255, 255, 255));
        editborder.setText("Edit Border");
        editborder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editborder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editborderActionPerformed(evt);
            }
        });

        borderinfo.setBackground(new java.awt.Color(0, 124, 220));
        borderinfo.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        borderinfo.setForeground(new java.awt.Color(255, 255, 255));
        borderinfo.setText("Border Info");
        borderinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borderinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderinfoActionPerformed(evt);
            }
        });

        removeborder.setBackground(new java.awt.Color(0, 124, 220));
        removeborder.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        removeborder.setForeground(new java.awt.Color(255, 255, 255));
        removeborder.setText("Remove Border");
        removeborder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeborder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeborderActionPerformed(evt);
            }
        });

        balance.setBackground(new java.awt.Color(0, 124, 220));
        balance.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("Balance");
        balance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        mill.setBackground(new java.awt.Color(0, 124, 220));
        mill.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        mill.setForeground(new java.awt.Color(255, 255, 255));
        mill.setText("Mill");
        mill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                millActionPerformed(evt);
            }
        });

        bill.setBackground(new java.awt.Color(0, 124, 220));
        bill.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        bill.setForeground(new java.awt.Color(255, 255, 255));
        bill.setText("Bill");
        bill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        addbazar.setBackground(new java.awt.Color(0, 124, 220));
        addbazar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        addbazar.setForeground(new java.awt.Color(255, 255, 255));
        addbazar.setText("Add Bazar");
        addbazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbazarActionPerformed(evt);
            }
        });

        editbazar.setBackground(new java.awt.Color(0, 124, 220));
        editbazar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        editbazar.setForeground(new java.awt.Color(255, 255, 255));
        editbazar.setText("Update Bazar");
        editbazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editbazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbazarActionPerformed(evt);
            }
        });

        bazardate.setBackground(new java.awt.Color(0, 124, 220));
        bazardate.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        bazardate.setForeground(new java.awt.Color(255, 255, 255));
        bazardate.setText("Bazar Date");
        bazardate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bazardate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazardateActionPerformed(evt);
            }
        });

        bazarlist.setBackground(new java.awt.Color(0, 124, 220));
        bazarlist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        bazarlist.setForeground(new java.awt.Color(255, 255, 255));
        bazarlist.setText("Bazar List");
        bazarlist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bazarlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazarlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(editborder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addborder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borderinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeborder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addbazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editbazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bazardate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bazarlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addbazar)
                        .addGap(18, 18, 18)
                        .addComponent(editbazar)
                        .addGap(18, 18, 18)
                        .addComponent(bazardate)
                        .addGap(18, 18, 18)
                        .addComponent(bazarlist))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(balance)
                        .addGap(18, 18, 18)
                        .addComponent(mill)
                        .addGap(18, 18, 18)
                        .addComponent(bill)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addborder)
                        .addGap(18, 18, 18)
                        .addComponent(editborder)
                        .addGap(18, 18, 18)
                        .addComponent(borderinfo)
                        .addGap(18, 18, 18)
                        .addComponent(removeborder)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exit.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        develop.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N
        develop.setForeground(new java.awt.Color(119, 136, 153));
        develop.setText("Developed By ");
        develop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                developMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                developMouseEntered(evt);
            }
        });

        aboutme.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N
        aboutme.setForeground(new java.awt.Color(119, 136, 153));
        aboutme.setText("Tuhin Hossain");
        aboutme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutmeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutmeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutmeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aboutmeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(develop)
                .addGap(1, 1, 1)
                .addComponent(aboutme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(develop)
                    .addComponent(aboutme))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void addborderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addborderActionPerformed
        this.hide();
        new AddBorder().setVisible(true);
    }//GEN-LAST:event_addborderActionPerformed

    private void borderinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderinfoActionPerformed
     this.hide();
     new BorderInfo().setVisible(true);
    }//GEN-LAST:event_borderinfoActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        this.hide();
        new balance().setVisible(true);
    }//GEN-LAST:event_balanceActionPerformed

    private void editborderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editborderActionPerformed
        this.hide();
        new editborder().setVisible(true);
    }//GEN-LAST:event_editborderActionPerformed

    private void removeborderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeborderActionPerformed
        this.hide();
        new RemoveBorder().setVisible(true);
    }//GEN-LAST:event_removeborderActionPerformed

    private void addbazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbazarActionPerformed
        this.hide();
        new AddBazar().setVisible(true);
    }//GEN-LAST:event_addbazarActionPerformed

    private void bazarlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazarlistActionPerformed
       this.hide();
       new bazarlist().setVisible(true);
    }//GEN-LAST:event_bazarlistActionPerformed

    private void bazardateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazardateActionPerformed
        this.hide();
        new bazardate().setVisible(true);
    }//GEN-LAST:event_bazardateActionPerformed

    private void millActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_millActionPerformed
       this.hide();
       new Mill().setVisible(true);
    }//GEN-LAST:event_millActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        this.hide();
        new bill().setVisible(true);
    }//GEN-LAST:event_billActionPerformed

    private void editbazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbazarActionPerformed
        this.hide();
        new editbazar().setVisible(true);
    }//GEN-LAST:event_editbazarActionPerformed

    private void developMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_developMouseClicked
        
    }//GEN-LAST:event_developMouseClicked

    private void developMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_developMouseEntered
        
        
    }//GEN-LAST:event_developMouseEntered

    private void aboutmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutmeMouseClicked
        
        if(autoOpen=="no") {
                new aboutme().setVisible(true);
                autoOpen = "yes";
                
                new aboutme().addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent e) 
                    {
                        autoOpen = "no";
                    }
                });
                }
        
    }//GEN-LAST:event_aboutmeMouseClicked

    private void aboutmeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutmeMouseEntered
        aboutme.setForeground(Color.red);
    }//GEN-LAST:event_aboutmeMouseEntered

    private void aboutmeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutmeMouseReleased
      
    }//GEN-LAST:event_aboutmeMouseReleased

    private void aboutmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutmeMouseExited
        aboutme.setForeground(Color.decode("#778899"));
    }//GEN-LAST:event_aboutmeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String propertyName = "sun.java2d.noddraw";
   System.setProperty(propertyName, "true");

   propertyName = "sun.java2d.d3d";
   System.setProperty(propertyName, "false");

   try 
   {
       javax.swing.UIManager.setLookAndFeel(MetalLookAndFeel.class.getName());
   }
   catch (Exception ex) 
   {
       ex.printStackTrace();
   }

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutme;
    private javax.swing.JButton addbazar;
    private javax.swing.JButton addborder;
    private javax.swing.JButton balance;
    private javax.swing.JButton bazardate;
    private javax.swing.JButton bazarlist;
    private javax.swing.JButton bill;
    private javax.swing.JButton borderinfo;
    private javax.swing.JLabel develop;
    private javax.swing.JButton editbazar;
    private javax.swing.JButton editborder;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mill;
    private javax.swing.JButton removeborder;
    // End of variables declaration//GEN-END:variables
}
