/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massmanagement;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuhin
 */
public class Register_form extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    

    /**
     * Creates new form Register_form
     */
    public Register_form() {
        initComponents();
        setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/heavy.png")));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        securitycode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(449, 340));
        setSize(new java.awt.Dimension(449, 340));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel1.setText("Full Name      :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 90, 103, 20);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel2.setText("Username      :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 124, 104, 20);

        fullname.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        getContentPane().add(fullname);
        fullname.setBounds(239, 89, 139, 26);

        username.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        getContentPane().add(username);
        username.setBounds(239, 123, 139, 26);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel3.setText("Password       :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 158, 104, 20);

        password.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        getContentPane().add(password);
        password.setBounds(239, 157, 139, 26);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel4.setText("Email               :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(72, 192, 106, 20);

        email.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        getContentPane().add(email);
        email.setBounds(239, 191, 139, 26);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel5.setText("Security Code :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 223, 113, 20);

        securitycode.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        securitycode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securitycodeActionPerformed(evt);
            }
        });
        securitycode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securitycodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                securitycodeKeyTyped(evt);
            }
        });
        getContentPane().add(securitycode);
        securitycode.setBounds(239, 220, 139, 26);

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 270, 81, 23);

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 270, 70, 23);

        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("*  All form must be filled");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 250, 130, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jframeback.jpg"))); // NOI18N
        jLabel6.setText(" ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -20, 450, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void securitycodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securitycodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securitycodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pass=password.getText().toString();
        String fname=fullname.getText();
        String uname=username.getText();
        String mail=email.getText();
        int secure=Integer.parseInt(securitycode.getText());
     if(fullname.getText().equals("")||password.getText().equals("")||username.getText().equals("")||email.getText().equals("")||securitycode.getText().equals("")){
     JOptionPane.showMessageDialog(this,"Please fill all the form");
     }
     else{
     
     
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
           con=DriverManager.getConnection("jdbc:derby:millmanage;create=true","app","");
            String sql="insert into login(username,password,email,security_code,fullname)values('"+uname+"','"+pass+"','"+mail+"',"+secure+",'"+fname+"')";
            Statement st=con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Successfully Registered");
            this.hide();
            new MassManagement().checkfor();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void securitycodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securitycodeKeyPressed

    }//GEN-LAST:event_securitycodeKeyPressed

    private void securitycodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securitycodeKeyTyped
                         
                     char c=evt.getKeyChar();
                    if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                     (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                     evt.consume();}
    }//GEN-LAST:event_securitycodeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField securitycode;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
